# Generated by Django 4.2.7 on 2024-12-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
