# Generated by Django 4.2.7 on 2024-12-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_order_postcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
    ]
