# Generated by Django 4.2.7 on 2024-12-12 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_subcategory_review_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
