# Generated by Django 4.2.7 on 2024-12-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteryear',
            name='year',
            field=models.CharField(choices=[('CAR', 'CAR'), ('2000 TO 2010', '2000 TO 2010'), ('2010 TO 2020', '2010 TO 2020')], max_length=60),
        ),
    ]
