# Generated by Django 4.2.7 on 2024-12-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_filteryear_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteryear',
            name='year',
            field=models.CharField(choices=[('CAR', 'CAR'), ('BIKE', 'BIKE')], max_length=60),
        ),
    ]
